name: fraud_project
version: "1.0.0"
config-version: 2

profile: ieee_fraud_detection

model-paths: ["models"]
analysis-paths: ["analyses"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  fraud_project:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: table
    marts:
      +schema: mart
      +materialized: table
    reporting:
      +schema: reporting
      +materialized: table
      +tags: ["reporting", "executive", "fraud"]
