select
    {{ fp_int(fp_quote('TransactionID')) }} as transaction_id,
    {{ fp_float(fp_quote('id_01')) }} as id_01,
    {{ fp_float(fp_quote('id_02')) }} as id_02,
    {{ fp_float(fp_quote('id_05')) }} as id_05,
    {{ fp_float(fp_quote('id_06')) }} as id_06,
    {{ fp_float(fp_quote('id_11')) }} as id_11,
    {{ fp_float(fp_quote('id_13')) }} as id_13,
    {{ fp_float(fp_quote('id_17')) }} as id_17,
    {{ fp_float(fp_quote('id_19')) }} as id_19,
    {{ fp_float(fp_quote('id_20')) }} as id_20,
    nullif(trim({{ fp_string(fp_quote('id_12')) }}), '') as id_12,
    nullif(trim({{ fp_string(fp_quote('id_15')) }}), '') as id_15,
    nullif(trim({{ fp_string(fp_quote('id_16')) }}), '') as id_16,
    nullif(trim({{ fp_string(fp_quote('id_28')) }}), '') as id_28,
    nullif(trim({{ fp_string(fp_quote('id_29')) }}), '') as id_29,
    nullif(trim({{ fp_string(fp_quote('id_31')) }}), '') as id_31,
    nullif(trim({{ fp_string(fp_quote('id_35')) }}), '') as id_35,
    nullif(trim({{ fp_string(fp_quote('id_36')) }}), '') as id_36,
    nullif(trim({{ fp_string(fp_quote('id_37')) }}), '') as id_37,
    nullif(trim({{ fp_string(fp_quote('id_38')) }}), '') as id_38,
    nullif(trim({{ fp_string(fp_quote('DeviceType')) }}), '') as device_type,
    nullif(trim({{ fp_string(fp_quote('DeviceInfo')) }}), '') as device_info
from {{ source('raw', 'train_identity') }}
