select
    {{ fp_int(fp_quote('TransactionID')) }} as transaction_id,
    {{ fp_smallint(fp_quote('isFraud')) }} as is_fraud,
    {{ fp_int(fp_quote('TransactionDT')) }} as transaction_dt,
    {{ fp_smallint("floor(" ~ fp_quote('TransactionDT') ~ " / 86400) + 1") }} as transaction_day,
    {{ fp_smallint("floor(" ~ fp_quote('TransactionDT') ~ " / 604800) + 1") }} as transaction_week,
    {{ fp_float(fp_quote('TransactionAmt')) }} as transaction_amount,
    nullif(trim({{ fp_string(fp_quote('ProductCD')) }}), '') as product_cd,
    {{ fp_smallint(fp_quote('card1')) }} as card1,
    {{ fp_float(fp_quote('card2')) }} as card2,
    {{ fp_float(fp_quote('card3')) }} as card3,
    nullif(trim({{ fp_string(fp_quote('card4')) }}), '') as card4,
    {{ fp_float(fp_quote('card5')) }} as card5,
    nullif(trim({{ fp_string(fp_quote('card6')) }}), '') as card6,
    {{ fp_float(fp_quote('addr1')) }} as addr1,
    {{ fp_float(fp_quote('addr2')) }} as addr2,
    {{ fp_float(fp_quote('dist1')) }} as dist1,
    {{ fp_float(fp_quote('dist2')) }} as dist2,
    nullif(trim({{ fp_string(fp_quote('P_emaildomain')) }}), '') as p_emaildomain,
    nullif(trim({{ fp_string(fp_quote('R_emaildomain')) }}), '') as r_emaildomain,
    {{ fp_float(fp_quote('C1')) }} as c1,
    {{ fp_float(fp_quote('C2')) }} as c2,
    {{ fp_float(fp_quote('C3')) }} as c3,
    {{ fp_float(fp_quote('C4')) }} as c4,
    {{ fp_float(fp_quote('C5')) }} as c5,
    {{ fp_float(fp_quote('C6')) }} as c6,
    {{ fp_float(fp_quote('C7')) }} as c7,
    {{ fp_float(fp_quote('C8')) }} as c8,
    {{ fp_float(fp_quote('C9')) }} as c9,
    {{ fp_float(fp_quote('C10')) }} as c10,
    {{ fp_float(fp_quote('C11')) }} as c11,
    {{ fp_float(fp_quote('C12')) }} as c12,
    {{ fp_float(fp_quote('C13')) }} as c13,
    {{ fp_float(fp_quote('C14')) }} as c14
from {{ source('raw', 'train_transaction') }}
