select
    "TransactionID"::bigint as transaction_id,
    "isFraud"::integer as is_fraud,
    "TransactionDT"::bigint as transaction_dt,
    cast(floor("TransactionDT" / 86400) + 1 as integer) as transaction_day,
    cast(floor("TransactionDT" / 604800) + 1 as integer) as transaction_week,
    "TransactionAmt"::double as transaction_amount,
    nullif(trim(cast("ProductCD" as varchar)), '') as product_cd,
    "card1"::integer as card1,
    "card2"::double as card2,
    "card3"::double as card3,
    nullif(trim(cast("card4" as varchar)), '') as card4,
    "card5"::double as card5,
    nullif(trim(cast("card6" as varchar)), '') as card6,
    "addr1"::double as addr1,
    "addr2"::double as addr2,
    "dist1"::double as dist1,
    "dist2"::double as dist2,
    nullif(trim(cast("P_emaildomain" as varchar)), '') as p_emaildomain,
    nullif(trim(cast("R_emaildomain" as varchar)), '') as r_emaildomain,
    "C1"::double as c1,
    "C2"::double as c2,
    "C3"::double as c3,
    "C4"::double as c4,
    "C5"::double as c5,
    "C6"::double as c6,
    "C7"::double as c7,
    "C8"::double as c8,
    "C9"::double as c9,
    "C10"::double as c10,
    "C11"::double as c11,
    "C12"::double as c12,
    "C13"::double as c13,
    "C14"::double as c14
from {{ source('raw', 'train_transaction') }}
