select
    "TransactionID"::bigint as transaction_id,
    "id_01"::double as id_01,
    "id_02"::double as id_02,
    "id_05"::double as id_05,
    "id_06"::double as id_06,
    "id_11"::double as id_11,
    "id_13"::double as id_13,
    "id_17"::double as id_17,
    "id_19"::double as id_19,
    "id_20"::double as id_20,
    nullif(trim(cast("id_12" as varchar)), '') as id_12,
    nullif(trim(cast("id_15" as varchar)), '') as id_15,
    nullif(trim(cast("id_16" as varchar)), '') as id_16,
    nullif(trim(cast("id_28" as varchar)), '') as id_28,
    nullif(trim(cast("id_29" as varchar)), '') as id_29,
    nullif(trim(cast("id_31" as varchar)), '') as id_31,
    nullif(trim(cast("id_35" as varchar)), '') as id_35,
    nullif(trim(cast("id_36" as varchar)), '') as id_36,
    nullif(trim(cast("id_37" as varchar)), '') as id_37,
    nullif(trim(cast("id_38" as varchar)), '') as id_38,
    nullif(trim(cast("DeviceType" as varchar)), '') as device_type,
    nullif(trim(cast("DeviceInfo" as varchar)), '') as device_info
from {{ source('raw', 'train_identity') }}
