version: 2

models:
  - name: stg_transactions
    columns:
      - name: transaction_id
        tests:
          - not_null
          - unique
      - name: is_fraud
        tests:
          - accepted_values:
              arguments:
                values: [0, 1]
                quote: false
  - name: stg_identity
    columns:
      - name: transaction_id
        tests:
          - not_null
          - unique
  - name: int_fraud_joined
    columns:
      - name: transaction_id
        tests:
          - not_null
          - unique
      - name: transaction_amount
        tests:
          - not_null
  - name: mart_daily_stats
    columns:
      - name: transaction_day
        tests:
          - not_null
          - unique
  - name: mart_model_predictions
    columns:
      - name: transaction_id
        tests:
          - not_null
